#!/bin/bash

METRICS=(
    "iqa_arniqa_metrics"
    "iqa_arniqa_clive_metrics"
    "iqa_arniqa_csiq_metrics"
    "iqa_arniqa_flive_metrics"
    "iqa_arniqa_kadid_metrics"
    "iqa_arniqa_live_metrics"
    "iqa_arniqa_spaq_metrics"
    "iqa_arniqa_tid_metrics"
    "iqa_brisque_metrics"
    "iqa_brisque_matlab_metrics"
    "iqa_clipiqa_metrics"
    "iqa_clipiqa__metrics"
    "iqa_clipiqa__rn50_512_metrics"
    "iqa_clipiqa__vitL14_512_metrics"
    "iqa_cnniqa_metrics"
    "iqa_dbcnn_metrics"
    "iqa_entropy_metrics"
    "iqa_hyperiqa_metrics"
    "iqa_ilniqe_metrics"
    "iqa_laion_aes_metrics"
    "iqa_liqe_metrics"
    "iqa_liqe_mix_metrics"
    "iqa_maniqa_metrics"
    "iqa_maniqa_kadid_metrics"
    "iqa_maniqa_pipal_metrics"
    "iqa_musiq_metrics"
    "iqa_musiq_ava_metrics"
    "iqa_musiq_paq2piq_metrics"
    "iqa_musiq_spaq_metrics"
    "iqa_nima_metrics"
    "iqa_nima_koniq_metrics"
    "iqa_nima_spaq_metrics"
    "iqa_nima_vgg16_ava_metrics"
    "iqa_niqe_metrics"
    "iqa_niqe_matlab_metrics"
    "iqa_nrqm_metrics"
    "iqa_paq2piq_metrics"
    "iqa_pi_metrics"
    "iqa_piqe_metrics"
    "iqa_topiq_iaa_metrics"
    "iqa_topiq_iaa_res50_metrics"
    "iqa_topiq_nr_metrics"
    "iqa_topiq_nr_flive_metrics"
    "iqa_topiq_nr_spaq_metrics"
    "iqa_tres_metrics"
    "iqa_tres_flive_metrics"
    "iqa_unique_metrics"
    "iqa_uranker_metrics"
    "iqa_wadiqam_nr_metrics"
)

for METRIC in "${METRICS[@]}"; do
    echo "Submitting job for $METRIC"
    sbatch run_metric.slurm "$METRIC"
done